use std::net::{IpAddr, Ipv6Addr};
use std::time::Duration;

use tarpc::{client, context};
use tarpc::tokio_serde::formats::Bincode;
use tokio::time::sleep;

use tarpc_shared::WorldClient;

pub mod tarpc_shared;

#[tokio::main]
async fn main() -> () {
    let s_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), 12001);
    let mut transport = tarpc::serde_transport::tcp::connect(&s_addr, Bincode::default);
    transport.config_mut().max_frame_length(usize::MAX);

    // WorldClient is generated by the service attribute. It has a constructor `new` that takes a
    // config and any Transport as input.
    let client = WorldClient::new(client::Config::default(), transport.await.expect("Client could not get transport")).spawn();

    println!("Client created");

    let hello = async move {
        // Send the request twice, just to be safe! ;)
        for i in 0..100 {
            let hello = tokio::select! {
                hello1 = client.hello(context::current(), format!("1:{}", i)) => { hello1 }
            };
            match hello {
                Ok(hello) => println!("{hello:?}"),
                Err(e) => panic!("{:?}", e),
            }
        }
    }.await;



    // Let the background span processor finish.
    sleep(Duration::from_micros(1)).await;

    ()
}